//Constants

//Boat stuff
#macro MAX_SPEED 2
#macro ACCELERATION 0.5

#macro MAX_TURN_SPEED 1
#macro TURN_ACCELERATION 0.1

#macro MAX_BACKWARDS_SPEED 1
#macro BACKWARDS_ACCELERATION 0.2

#macro DECELLERATION 0.9